### PR TITLE
Upgrade syn and quote to 1.0.

### LINKED ISSUE #5: update syn & quote dependencies
I tried using rust-reduce to troubleshoot https://github.com/immunant/c2rust/issues/183 and see if I reduce the cause of `cannot determine resolution for the derive macro` to something more manageable, but I get this error:

```
Camerons-MacBook-Pro:openconnect-rust cameron$ RUST_BACKTRACE=1 /Users/cameron/github/rust-reduce/target/release/rust-reduce ./reduce.sh lib.rs
thread 'main' panicked at 'Unable to parse file: Error("expected one of: `for`, parentheses, `fn`, `unsafe`, `extern`, identifier, `::`, `<`, square brackets, `*`, `&`, `!`, `impl`, `_`, lifetime")', src/libcore/result.rs:1165:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: <syn_inline_mod::resolver::FsResolver as syn_inline_mod::resolver::FileResolver>::resolve
  11: <syn_inline_mod::visitor::Visitor<R> as syn::gen::visit_mut::VisitMut>::visit_item_mod_mut
  12: <syn_inline_mod::visitor::Visitor<R> as syn::gen::visit_mut::VisitMut>::visit_item_mod_mut
  13: syn_inline_mod::InlinerBuilder::parse_and_inline_modules
  14: rust_reduce::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

After troubleshooting it for a bit, I think it would be good to update all of the syn / quote/ proc_macro2 dependencies.

https://github.com/jethrogb/rust-reduce/blob/3c54ffdf4629f6bd3adeef8aabda412acbdc2fd6/Cargo.toml#L10-L13

Latest versions:
https://github.com/dtolnay/syn 1.0.4
https://github.com/dtolnay/quote 1.0.2

I think https://github.com/TedDriggs/syn-inline-mod will also need some assistance upgrading. Currently on:
``` toml
syn = { version = "0.15.26", features = ["full", "visit-mut"] }
proc-macro2 = { version = "0.4", features = ["span-locations"] }
```
Latest:
https://github.com/dtolnay/syn 1.0.4
https://github.com/dtolnay/quote 1.0.2

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #5.

### CODE REVIEW

**Review by jethrogb — APPROVED** [review]
Thanks!

**Comment by mati865** [comment]
Is there anything preventing this from being merged?

**Comment by programmerjake** [comment]
can this be merged or have someone else take over maintainership? maybe @eddyb?

**Comment by programmerjake** [comment]
thanks!

**Pull request merged**
